### ISSUE TITLE
Channel B support

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [dcrystalj/hx711py3#3]
Is it planned to support 2 loadcells? First on Channel A and second on Channael B?

I found out, that
Channel A is gain 128 and 64
Channel B is gain 32

**Comment by dcrystalj** [comment]
Can't you just instantiate 2 class instances then?
```
a = Scale(HX711(dout=5, pd_sck=6, gain=128, bitsToRead=24))
b = Scale(HX711(dout=7, pd_sck=8, gain=32, bitsToRead=24))
```

Or you mean 2 load cells on 1  HX711 ?
Then you just need to use setGain() before reading weight i guess.

**Comment by Tronje-the-Falconer** [comment]
Oh yes, you are right.
