### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by UlasBaunie** [dcrystalj/hx711py3#4]
1. Will you help me with the whole calibration please? I believe I managed to get the  "ReferenceUnit" but once I put 5kg on the scale it goes up to 58.6kg

**Comment by dcrystalj** [comment]
you can see the instructions here: https://github.com/dcrystalj/hx711py3/blob/master/example.py

One possibility:
* set `reference_unit` to `1`
* call `get_weight()` when nothing is on the scale and save it to variable `mes1`.
* put 5kg on the scale
* call `get_weight()` with 5kg on it and save it to variable `mes2`
*  calculate `(mes2 - mes1) / 5000` == `new_reference_unit` 

voila this is your reference unit. 
In example i used 21 which was the value (of new_reference_unit) i got after the procedure described above.

**Comment by UlasBaunie** [comment]
Thank you for the help

 

One more thing… sorry I am new to programing

The “call get_weight(“) how do I do it, do I run the spikeless_example.py or is it a python command I need to run on its own?

**Comment by dcrystalj** [comment]
you can run example.py 

just change line `hx.setReferenceUnit(21)` to `hx.setReferenceUnit(1)`

**Comment by UlasBaunie** [comment]
The numbers I’m getting is very random

I have attached 2 .txt files with the readings that I get

 

1 = Before 5kg

2 = after 5kg

**Comment by dcrystalj** [comment]
please dont reply using email. your are sending weird messages to issue.

Random values are normal. but you might have:
* bad wiring
* electrical interferences from outside
* bad grounding
* bad sensor? do you have exactly same sensor?
* broken pi
* ... much more

**Comment by UlasBaunie** [comment]
sorry for that and thanks for the help
