### ISSUE TITLE
测量结果值飘的很厉害

### ISSUE THREAD

**Issue by lixunhui** [dcrystalj/hx711py3#7]
您好，我测量结果一直飘的很厉害，是怎么回事，能帮我调试一下嘛

**Comment by dcrystalj** [comment]
sorry. English only. 
Look for spikless example and try to tune this params: `samples=20, spikes=4, sleep=0.1` 
Try to make samples size bigger

**Comment by lixunhui** [comment]
> sorry. English only.
> Look for spikless example and try to tune this params: `samples=20, spikes=4, sleep=0.1`
> Try to make samples size bigger

Hello, after I run according to your Demo, the result will be a random value, which will not change with or without weights，
Could you give me your email address?

**Comment by dcrystalj** [comment]
we can discuss here, no problem. You can find me hx711py3@tomazic.pro

Random value might be problem if you didnt calc reference unit correctly. see `example.py`
